config/routes.rb
Pedometer::Application.routes.draw do
  get "devices/dashboard"
  get "devices/dashboard_mobile"
  resources :devices

end

app/models/device.rb
class Device < ActiveRecord::Base
  attr_accessible :deviceid

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/devices_controller.rb
class DevicesController < ApplicationController
  # GET /devices
  # GET /devices.json
  def index
    @devices = Device.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @devices }
    end
  end

  # GET /devices/1
  # GET /devices/1.json
  def show
    @device = Device.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @device }
    end
  end

  # GET /devices/new
  # GET /devices/new.json
  def new
    @device = Device.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @device }
    end
  end

  # GET /devices/1/edit
  def edit
    @device = Device.find(params[:id])
  end

  # POST /devices
  # POST /devices.json
  def create
    @device = Device.new(params[:device])

    respond_to do |format|
      if @device.save
        format.html { redirect_to @device, notice: 'Device was successfully created.' }
        format.json { render json: @device, status: :created, location: @device }
      else
        format.html { render action: "new" }
        format.json { render json: @device.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /devices/1
  # PUT /devices/1.json
  def update
    @device = Device.find(params[:id])

    respond_to do |format|
      if @device.update_attributes(params[:device])
        format.html { redirect_to @device, notice: 'Device was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @device.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /devices/1
  # DELETE /devices/1.json
  def destroy
    @device = Device.find(params[:id])
    @device.destroy

    respond_to do |format|
      format.html { redirect_to devices_url }
      format.json { head :no_content }
    end
  end

  def dashboard
    #@device = Device.find(params[:id])

    render :dashboard
  end

  def dashboard_mobile
    #@device = Device.find(params[:id])

    render :dashboard_mobile
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devices_helper.rb
module DevicesHelper
end

app/views/devices/_form.html.erb
<%= form_for(@device) do |f| %>
  <% if @device.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@device.errors.count, "error") %> prohibited this device from being saved:</h2>

      <ul>
      <% @device.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div class="field">
      <%= f.label :deviceid %><br />
      <%= f.text_field :deviceid %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/devices/dashboard.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RGraph: HTML5 canvas graph library - a basic example</title>
  <script src="libraries/RGraph.common.core.js" ></script>
  <script src="libraries/RGraph.bar.js" ></script>
</head>
<body>
<h1>Pedometer</h1>
<h2>RGraph: HTML5 canvas graph for steps Counter</h2>
<!-- This is the canvas that the graph is drawn on -->
<canvas id="myBar" width="700" height="250">[No canvas support]</canvas>

<!--This creates and displays the graph.
We can call this from the window.onload event,
allowing you to put it in your pages header. -->
<script>
    window.onload = function ()
    {
        var bar = new RGraph.Bar('myBar', [120,130,160,150,160,190,190,120,230,160,130,240]);
        bar.Set('chart.colors', ['red']);
        bar.Set('chart.title', 'A basic graph (big, but basic)');
        bar.Set('chart.labels', ['Jan', 'Feb', 'Mar', 'Apr', 'May',
            'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']);
        bar.Draw();
    }
</script>
<p>
<div style="width:700px">
  <h5>Key points</h5>
  Using a pedometer or step counter is an easy and fun way to track how active you are. It adds up all the steps you take during the day.
  Using a pedometer can remind you to walk more. A quick check may show that you need more steps for the day.
  Using a pedometer can help you set goals to take more steps in a day. You may need to find creative ways to add more steps, but walking more will help you get more exercise, feel better, and stay healthy.

</div>
</p>
</body>
</html>

app/views/devices/dashboard_mobile.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RGraph: HTML5 canvas graph library - a basic example</title>
  <script src="libraries/RGraph.common.core.js" ></script>
  <script src="libraries/RGraph.bar.js" ></script>
</head>
<body>
<div style="position: absolute; left: 0px; top: 0px; overflow: hidden; width: 100%; height: 100%; z-index: 0;">
  <h1>Pedometer</h1>
  <h2>Mobile steps Counter</h2>
  <!-- This is the canvas that the graph is drawn on -->
  <canvas id="myBar" width="400" height="250">[No canvas support]</canvas>

  <!--This creates and displays the graph.
We can call this from the window.onload event,
allowing you to put it in your pages header. -->
  <script>
      window.onload = function ()
      {
          var bar = new RGraph.Bar('myBar', [120,130,160,150,160,190,190,120,230,160,130,240]);
          bar.Set('chart.colors', ['red']);
          bar.Set('chart.title', 'A basic graph (big, but basic)');
          bar.Set('chart.labels', ['Jan', 'Feb', 'Mar', 'Apr', 'May',
              'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']);
          bar.Draw();
      }
  </script>
  <p>
  <div style="width:400px">
    <h5>Key points</h5>
    Using a pedometer or step counter is an easy and fun way to track how active you are. It adds up all the steps you take during the day.
    Using a pedometer can remind you to walk more. A quick check may show that you need more steps for the day.
    Using a pedometer can help you set goals to take more steps in a day. You may need to find creative ways to add more steps, but walking more will help you get more exercise, feel better, and stay healthy.

  </div>
  </p>
</div>
</body>
</html>

app/views/devices/edit.html.erb
<h1>Editing device</h1>

<%= render 'form' %>

<%= link_to 'Show', @device %> |
<%= link_to 'Back', devices_path %>

app/views/devices/index.html.erb
<h1>Listing devices</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @devices.each do |device| %>
  <tr>
    <td>id = <%=device.deviceid%></td>
    <td><%= link_to 'Show', device %></td>
    <td><%= link_to 'Edit', edit_device_path(device) %></td>
    <td><%= link_to 'Destroy', device, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Device', new_device_path %>

app/views/devices/new.html.erb
<h1>New device</h1>

<%= render 'form' %>

<%= link_to 'Back', devices_path %>

app/views/devices/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_device_path(@device) %> |
<%= link_to 'Back', devices_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pedometer</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>